name: hws-ios
fileGroups:
  - configs
configFiles:
  Debug: configs/Debug.xcconfig
  Release: configs/Release.xcconfig
targets:
  hws-ios:
    type: application
    platform: iOS
    sources: hws-ios
    configFiles:
      Debug: configs/hws-ios-Debug.xcconfig
      Release: configs/hws-ios-Release.xcconfig
    settings:
      CURRENT_PROJECT_VERSION: 1
    dependencies:
      - package: APIKit
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
      - package: RxSwift
        product: RxSwift
    preBuildScripts:
    - path: ./scripts/xcodegen/swiftformat.sh
      name: Run SwiftFormat
    - path: ./scripts/xcodegen/swiftlint.sh
      name: Run SwiftLint
    - script: |
        SCRIPT_PATH="${PODS_ROOT}/Apollo/scripts"
        cd "${SRCROOT}/${TARGET_NAME}"
        "${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="schema.json" API.swift
        "${SCRIPT_PATH}"/run-bundled-codegen.sh schema:download --endpoint="https://hwsapi.hysrtr.com/query"
      name: Generate Apollo GraphQL API
packages:
  APIKit:
    url: https://github.com/ishkawa/APIKit
    version: 5.1.0
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    version: 6.0.0